name: cfip

on:
  schedule:
    - cron: '00 2 * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - run: echo "start update"
     
    - name: Check my code
      uses: actions/checkout@main
      
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 2  
        
    - name: Remove old data
      run: rm -rf ./ip*
    
    - name: Get source data
      run: |
        if [ -z "${{ secrets.DOWNLOAD_URL }}" ]; then
          echo "Error: DOWNLOAD_URL is not set"
          exit 1
        fi
        wget -t 3 --timeout=30 -nd -np -npH "${{ secrets.DOWNLOAD_URL }}" -O ip.zip
        file ip.zip
        unzip -t ip.zip
        unzip ip.zip -d ./ips
        ls -l ./ips/
        rm ip.zip

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r ./requirements.txt

    - name: Run main.py
      run: |
        ls -l ./ips/
        python main.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --cached --exit-code || git commit -m "update result" && git push origin main
